version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram/udagram-frontend
            npm install
      - run:
          name: Install API Dependencies
          command: |
            cd udagram/udagram-api
            npm install
      - run:
          name: Build Front-End
          command: |
            cd udagram/udagram-frontend
            npm run build
      - run:
          name: Build API
          command: |
            cd udagram/udagram-api
            npm run build
      - run:
          name: Check if Front-End Build Directory Exists
          command: |
            cd udagram/udagram-frontend
            if [ -d "./www" ]; then
              echo "Build directory ./www exists."
              ls -la ./www
            else
              echo "Build directory ./www does not exist."
              exit 1
            fi
      - persist_to_workspace:
          root: udagram/udagram-frontend
          paths:
            - www

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy Front-End
          command: |
            cd /workspace/udagram/udagram-frontend
            if [ -d "./www" ]; then
              aws s3 cp --recursive ./www/ s3://user3354372-udagram/ --profile default
              aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./www/index.html s3://user3354372-udagram/ --profile default
            else
              echo "Build directory ./www does not exist."
              exit 1
            fi
      - run:
          name: Deploy API
          command: |
            cd udagram/udagram-api
            eb init -p nodejs --region us-east-1
            eb list --profile default
            eb use udagram-api-dev --profile default
            eb deploy --profile default

workflows:
  udagram:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
