POSTGRES_USERNAME=$POSTGRES_USERNAME
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_DB=$POSTGRES_DB
AWS_BUCKET=$AWS_BUCKET
AWS_REGION=$AWS_REGION
AWS_PROFILE=$AWS_PROFILE
JWT_SECRET=$JWT_SECRET
URL=$URL

echo "POSTGRES_USERNAME=$POSTGRES_USERNAME"
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
echo "POSTGRES_HOST=$POSTGRES_HOST"
echo "POSTGRES_DB=$POSTGRES_DB"
echo "AWS_BUCKET=$AWS_BUCKET"
echo "AWS_REGION=$AWS_REGION"
echo "AWS_PROFILE=$AWS_PROFILE"
echo "JWT_SECRET=$JWT_SECRET"
echo "URL=$URL"

echo "Thiết lập biến môi trường trong Elastic Beanstalk..."
eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME \
           POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
           POSTGRES_HOST=$POSTGRES_HOST \
           POSTGRES_DB=$POSTGRES_DB \
           AWS_BUCKET=$AWS_BUCKET \
           AWS_REGION=$AWS_REGION \
           AWS_PROFILE=$AWS_PROFILE \
           JWT_SECRET=$JWT_SECRET \
           URL=$URL \
           --profile your-aws-profile-name

